name: ServerSync
version: 1.0
author: michaelkrauty
main: me.michaelkrauty.ServerSync.Main
commands:
  serversync:
    usage: /ss
    aliases: ss
  channel:
    usage: /channel <channel>
  nickname:
    usage: /nickname <nickname>
    aliases: nick
  realname:
    usage: /realname <nickname>
  ban:
    usage: /ban <player> [reason]
  tempban:
    usage: /tempban <player> <duration> [reason]
  mute:
    usage: /mute <player> <duration> [reason]